export const ADD_MESSAGE = 'ADD_MESSAGE';
export const MESSAGE_FROM_SERVER = 'MESSAGE_FROM_SERVER';
export const MESSAGE_FROM_CLIENT = 'MESSAGE_FROM_CLIENT';
export const ADD_USER = 'ADD_USER';
export const USERS_LIST = 'USERS_LIST';
